version: "3"
services:
  db:
    image: mysql:5.6
    env_file: .env
  wordpress:
    image: mobingi/ubuntu-apache2-php7:7.1
    env_file: .env
    ports:
      - '8000:80'
    volumes:
      - /Users/hikarumaruyama/src/github.com/hmaruyama/blog-wordpress:/var/www/html
    depends_on:
      - db
